config/routes.rb
Rails.application.routes.draw do
  devise_for :views
  root 'homes#index'
  devise_for :users
  resources :dashboard, only: [:index]
  resources :concerts, only: [:index, :show, :new] do
    resources :predictions, only: [:new, :create, :show, :edit, :update, :destroy]
  end
  resources :about, only: [:index]

end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  def index
    # TOOK OUT BUGGY RANDOM CONCERT CALLS FOR NOW
    # concert = RandomConcertGenerator.new
    # @random_concert = concert.pull_random_concert_from_database

    concert_loader = ConcertLoader.new
    @latest_setlist = concert_loader.concert_builder(
    "https://api.phish.net/api.json?api=2.0&method=pnet.shows.setlists.latest"
    )
  end
end

app/views/dashboard/index.html.erb
<div class="row">
  <div class="large-9 columns" role="content">

    <%= image_tag("phishbowl-full-logo.png") %>

      <div class="panel phishbowlpanel">
        <h4 class="hide-for-small">How it works<hr/></h4>
        <h5 class="subheader">Phantasy Phishbowl is an epic game of setlist speculation for Phans of the band Phish. Here are the rules:</h5>
        <ol>
          <li>For each concert, a player predicts songs Phish will play on a given date.</li>
          <li>Players must pick a set one opener and closer, a set two opener and closer, encore, and one random pick.</li>
          <li>Players are awarded three points for getting a pick in the right spot, one point if the song appears anywhere in the setlist, and two points if the random pick is played.</li>
          <li>When Phish is not on tour, players can guess which songs Phish played during a recent show.</li>
        </ol>
      </div>

    <div class="panel phishbowlpanel">
      <h5>Play Phantasy Phishbowl</h5>
      <h6 class="subheader">Practice with a recent show</h6>
      <%= link_to "Play with recent concert", concert_path(@latest_setlist), class: "button radius enter" %>
    </div>

    <div class="panel phishbowlpanel">
      <h5>About</h5>
      <h6 class="subheader">More information on Phantasy Phishbowl</h6>
      <%= link_to "About", about_index_path, class: "button radius enter" %>
    </div>

  </div>

  <aside class="large-3 columns">
    <div class="panel setlistside">
      <h5>Latest Show</h5>
      <h6><%= @latest_setlist.concert_date %></h6>
      <h6><%= @latest_setlist.city %> , <%= @latest_setlist.state %></h6>
      <% @latest_setlist.concert_songs.each do |concert_song| %>
        <ul>
          <li><%= concert_song.song.song_name %></li>
        </ul>
      <% end %>
      <p></p>
    </div>
  </aside>

</div>