config/routes.rb
Rails.application.routes.draw do
  devise_for :views
  root 'homes#index'
  devise_for :users
  resources :dashboard, only: [:index]
  resources :concerts, only: [:index, :show, :new] do
    resources :predictions, only: [:new, :create, :show, :edit, :update, :destroy]
  end
  resources :about, only: [:index]

end

app/models/concert.rb
class Concert < ActiveRecord::Base
  has_many :predictions
  has_many :concert_songs
  has_many :songs,
    through: :concert_songs

  validates :concert_date, uniqueness: true
end

app/controllers/concerts_controller.rb
class ConcertsController < ApplicationController
  def index
    # Upcoming shows?
  end

  def show
    @concert = Concert.find(params[:id])
  end
end

app/views/concerts/index.html.erb
<h1>Concert Index Page</h1>
<!-- <ul class="small-block-grid-3">
  <% @concerts.each do |concert| %>
    <h3><%= link_to concert.concert_date, concert_path(concert) %></h3>
    <li><%= concert.venue %></li>
    <li><%= concert.city %> , <%= concert.state %></li>
  <% end %>
</ul> -->


<%=link_to "Play with Random Show", concert_path(@random_concert) %>

app/views/concerts/new.html.erb
<h1>Add a new show </h1>

<ul class="small-block-grid-3">
  <!-- <% @upcoming.each do |concert| %>
    <h3><%= concert.venue %></h3>
    <li><%= concert.state %> , <%= concert.venue %></li>
    <li><%= link_to concert.venue, concert_path(concert) %></li> -->
  <!-- <% end %> -->

  <h2>Random Show</h1>
    <h3><%= @random_show.concert_date %></h3>
    <li><%= @random_show.venue %></li>
    <li><%= @random_show.city %> , <%= @random_show.state %></li>
    <li><%= link_to concert.venue, concert_path(concert) %></li>
</ul>

app/views/concerts/show.html.erb
<div class="row">
  <hr>
  <div class="large-12 columns intro concert-page phishbowlpanel">
    <h1><%= @concert.venue %></h1>
    <h2><%= @concert.concert_date %></h2>
    <h3><%=@concert.city %> , <%= @concert.state %></h3>
    <%= link_to "Play Phantasy Phishbowl!",  new_concert_prediction_path(@concert), class: "button radius enter" %>
  </div>
</div>

<div class="row">
  <div class="large-4 columns intro concert-page phishbowlpanel">

    <h2>Prediction</h2>
    <ul>
      <% @concert.predictions.each do |picks| %>
        <li>Set One Opener: <%= picks.set_one_opener_song.song_name %></li>
        <li>Set One Closer: <%= picks.set_one_closer_song.song_name %></li>
        <li>Set Two Opener: <%= picks.set_two_opener_song.song_name %></li>
        <li>Set Two Closer: <%= picks.set_two_closer_song.song_name %></li>
        <li>Encore: <%= picks.encore_song.song_name %></li>
        <li>Random Song: <%= picks.random_pick_song.song_name %></li>
        <%= link_to "Check Score", concert_prediction_path(@concert, picks.id), class: "button radius enter checkscore" %>
        <%= link_to "Edit", edit_concert_prediction_path(@concert, picks.id), class: "button radius enter checkscore" %>
        <%= link_to "Delete", concert_prediction_path(@concert, picks.id), method: :delete, data: { confirm: 'Are you sure?' }, class: "button radius enter checkscore" %>
      <% end %>
    </ul>
    </div>
  </div>


</div>