config/routes.rb
Rails.application.routes.draw do
  devise_for :views
  root 'homes#index'
  devise_for :users
  resources :dashboard, only: [:index]
  resources :concerts, only: [:index, :show, :new] do
    resources :predictions, only: [:new, :create, :show, :edit, :update, :destroy]
  end
  resources :about, only: [:index]

end

app/controllers/about_controller.rb
class AboutController < ApplicationController
  def index
    concert_loader = ConcertLoader.new
    @latest_setlist = concert_loader.concert_builder(
    "https://api.phish.net/api.json?api=2.0&method=pnet.shows.setlists.latest"
    )
  end
end

app/views/about/index.html.erb
<div class="row">
  <div class="large-9 columns" role="content">

    <%= image_tag("phishbowl-full-logo.png") %>

    <div class="panel phishbowlpanel">
      <h4 class="hide-for-small">About Phantasy Phishbowl<hr/></h4>
      <p>
        Phantasy Phishbowl was built using the Ruby on Rails web framework, by Nathan Burgess, a web developer from Vermont now living in Mass.
        The app makes use of the API from Phish.net to load song and concert data. Currently the app only allows users to make predictions against the most recent show,
        but in the future it will allow users to create a fantasy-football style league, where you can play with your friends. Users will be able to predict the setlist for an upcoming show,
        and the app will automatically assign points based on your picks. Thanks for checking out Phantasy Phishbowl! Check me out on Twitter and GitHub (below).
      </p>
    </div>

    <div class="panel phishbowlpanel">
      <%= link_to "Back", dashboard_index_path, class: "button radius enter" %>
    </div>

  </div>

  <aside class="large-3 columns">
    <div class="panel setlistside">
      <h5>Latest Show</h5>
      <h6><%= @latest_setlist.concert_date %></h6>
      <h6><%= @latest_setlist.city %> , <%= @latest_setlist.state %></h6>
      <% @latest_setlist.songs.each do |song| %>
      <ul>
        <li><%= song.song_name %></li>
      </ul>
      <% end %>
      <p></p>
    </div>
  </aside>

</div>